---
# Database secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-database
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: authelia-database
    creationPolicy: Owner
  data:
    - secretKey: database
      remoteRef:
        key: authelia-database
        property: value
    - secretKey: database-user
      remoteRef:
        key: authelia-database-user
        property: value
    - secretKey: database-password
      remoteRef:
        key: authelia-database-password
        property: value
---
# Core Authelia secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: authelia-jwt-secret
        property: value
    - secretKey: session-secret
      remoteRef:
        key: authelia-session-secret
        property: value
    - secretKey: encryption-key
      remoteRef:
        key: authelia-encryption-key
        property: value
    - secretKey: session-default-name
      remoteRef:
        key: authelia-session-default-name
        property: value
    - secretKey: session-project-tld-name
      remoteRef:
        key: authelia-session-project-tld-name
        property: value
---
# OIDC secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: authelia-oidc
    creationPolicy: Owner
  data:
    - secretKey: oidc-hmac-secret
      remoteRef:
        key: authelia-oidc-hmac-secret
        property: value
    - secretKey: oidc-gitea-client-secret
      remoteRef:
        key: authelia-oidc-gitea-client-secret
        property: value
    - secretKey: gitea-oidc-client-id
      remoteRef:
        key: gitea-oidc-client-id
        property: value
---
# User configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: authelia-users
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users.yml: |
          users:
            {{ `{{ .user_1_username }}` }}:
              displayname: "{{ `{{ .user_1_display_name }}` }}"
              password: "{{ `{{ .user_1_password }}` }}"
              email: {{ `{{ .user_1_email }}` }}
              groups:
                - admin
                - media
                - print

            {{ `{{ .user_2_username }}` }}:
              displayname: "{{ `{{ .user_2_display_name }}` }}"
              password: "{{ `{{ .user_2_password }}` }}"
              email: {{ `{{ .user_2_email }}` }}
              groups:
                - media
                - print
  data:
    - secretKey: user_1_username
      remoteRef:
        key: authelia-user-1-username
        property: value
    - secretKey: user_1_display_name
      remoteRef:
        key: authelia-user-1-display-name
        property: value
    - secretKey: user_1_password
      remoteRef:
        key: authelia-user-1-password
        property: value
    - secretKey: user_1_email
      remoteRef:
        key: authelia-user-1-email
        property: value
    - secretKey: user_2_username
      remoteRef:
        key: authelia-user-2-username
        property: value
    - secretKey: user_2_display_name
      remoteRef:
        key: authelia-user-2-display-name
        property: value
    - secretKey: user_2_password
      remoteRef:
        key: authelia-user-2-password
        property: value
    - secretKey: user_2_email
      remoteRef:
        key: authelia-user-2-email
        property: value
