---
# Database secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-database
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authelia-database
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authelia-database
    - extract:
        key: authelia-database-user
    - extract:
        key: authelia-database-password
---
# Core Authelia secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authelia-jwt-secret
    - extract:
        key: authelia-session-secret
    - extract:
        key: authelia-encryption-key
    - extract:
        key: authelia-session-default-name
    - extract:
        key: authelia-session-project-tld-name
---
# OIDC secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authelia-oidc
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authelia-oidc-hmac-secret
    - extract:
        key: authelia-oidc-gitea-client-secret
    - extract:
        key: gitea-oidc-client-id
---
# User configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authelia-users
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users.yml: |
          users:
            {{ `{{ .user_1_username }}` }}:
              displayname: "{{ `{{ .user_1_display_name }}` }}"
              password: "{{ `{{ .user_1_password }}` }}"
              email: {{ `{{ .user_1_email }}` }}
              groups:
                - admin
                - media
                - print

            {{ `{{ .user_2_username }}` }}:
              displayname: "{{ `{{ .user_2_display_name }}` }}"
              password: "{{ `{{ .user_2_password }}` }}"
              email: {{ `{{ .user_2_email }}` }}
              groups:
                - media
                - print
  dataFrom:
    - extract:
        key: authelia-user-1-username
    - extract:
        key: authelia-user-1-display-name
    - extract:
        key: authelia-user-1-password
    - extract:
        key: authelia-user-1-email
    - extract:
        key: authelia-user-2-username
    - extract:
        key: authelia-user-2-display-name
    - extract:
        key: authelia-user-2-password
    - extract:
        key: authelia-user-2-email
