apiVersion: v2
name: dispatchr-social-staging
description: Dispatchr Social - Staging Environment
type: application
version: 1.0.0
appVersion: "v0.1.50"
keywords:
  - dispatchr
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
dependencies:
  - name: staging-app
    version: "0.1.0"
    repository: "file://../../charts/staging-app"
