---
# ClusterSecretStore for Bitwarden Secrets Manager
# This allows all namespaces to pull secrets from Bitwarden
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      # Reference to secret containing Bitwarden access token
      auth:
        secretRef:
          credentials:
            name: bitwarden-credentials
            namespace: external-secrets-system
            key: token

      # Organization ID (get from Bitwarden Secrets Manager settings)
      organizationID: "4650c1c8-8d22-4073-8a7d-b3cf011d5ff2"

      # Project ID (optional - scope to specific project)
      # If you want to scope ESO to your existing BWS project:
      projectID: "2ae99c5f-e9d6-4b1d-8a12-b3d000254de6"
