---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radarr-uhd.fullname" . }}
  labels:
    {{- include "radarr-uhd.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "radarr-uhd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "radarr-uhd.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command:
        - sh
        - -c
        - |
          chown -R {{ .Values.env.PUID }}:{{ .Values.env.PGID }} /config
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: radarr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        - name: PUID
          value: {{ .Values.env.PUID | quote }}
        - name: PGID
          value: {{ .Values.env.PGID | quote }}
        volumeMounts:
        - name: config
          mountPath: /config
        {{- if .Values.persistence.media.enabled }}
        - name: movies-uhd
          mountPath: {{ .Values.persistence.media.moviesUhd.mountPath }}
        - name: downloads-movies-uhd
          mountPath: {{ .Values.persistence.media.downloadsMoviesUhd.mountPath }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "radarr-uhd.fullname" . }}-config
      {{- if .Values.persistence.media.enabled }}
      - name: movies-uhd
        hostPath:
          path: {{ .Values.persistence.media.moviesUhd.hostPath }}
          type: Directory
      - name: downloads-movies-uhd
        hostPath:
          path: {{ .Values.persistence.media.downloadsMoviesUhd.hostPath }}
          type: Directory
      {{- end }}
