---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcr-pull-secret-dispatchr
  labels:
    {{- include "dispatchr-staging.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-staging-dispatchr
    kind: ClusterSecretStore
  target:
    name: gcr-pull-secret-dispatchr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{`{{ printf "{\"auths\":{\"us-central1-docker.pkg.dev\":{\"username\":\"_json_key\",\"password\":%s}}}" (.gcrKey | toJson) }}`}}
  data:
    - secretKey: gcrKey
      remoteRef:
        key: {{ .Values.gcrPullSecret.bitwardenKey }}
