apiVersion: v2
name: sonarr-anime
description: Sonarr - Smart PVR for anime
type: application
version: 1.0.0
appVersion: "4.0.17"

keywords:
  - sonarr
  - pvr
  - anime
  - arr

maintainers:
  - name: Homelab Admin
