apiVersion: v2
name: atlas-staging
description: Atlas control plane - Staging Environment
type: application
version: 1.0.0
appVersion: "0.1.0"
keywords:
  - atlas
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
dependencies:
  - name: staging-app
    version: "0.7.2"
    repository: "file://../../charts/staging-app"
