apiVersion: v2
name: jellyfin
description: Jellyfin - The Free Software Media System
type: application
version: 1.0.0
appVersion: "10.11.8"

keywords:
  - jellyfin
  - media
  - streaming

maintainers:
  - name: Homelab Admin
