---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-staging-jlshaw
  labels:
    {{- include "jlshaw-staging.labels" . | nindent 4 }}
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            name: {{ .Values.bitwarden.credentialsSecret }}
            namespace: external-secrets-system
            key: token
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets-system.svc.cluster.local:9998
      organizationID: {{ .Values.bitwarden.organizationID | quote }}
      projectID: {{ .Values.bitwarden.projectID | quote }}
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets-system
        key: ca.crt
