---
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  labels:
    {{- include "jlshaw-staging.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}

  secretStoreRef:
    name: bitwarden-staging-jlshaw
    kind: ClusterSecretStore

  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner

  {{- if .Values.externalSecrets.secrets }}
  data:
  {{- range .Values.externalSecrets.secrets }}
  - secretKey: {{ .name }}
    remoteRef:
      key: {{ .key }}
  {{- end }}
  {{- end }}
{{- end }}
