---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
  namespace: default
  labels:
    app: authelia
spec:
  serviceName: authelia
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9959"
        prometheus.io/path: /metrics
    spec:
      priorityClassName: authelia-priority
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: yellowtalon

      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch

      containers:
      - name: authelia
        image: authelia/authelia:latest
        imagePullPolicy: Always

        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

        env:
        - name: TZ
          value: America/Chicago

        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        - name: metrics
          containerPort: 9959
          protocol: TCP

        volumeMounts:
        - name: config
          mountPath: /config/configuration.yml
          subPath: configuration.yml
          readOnly: true
        - name: users
          mountPath: /config/users.yml
          subPath: users.yml
          readOnly: true
        - name: assets
          mountPath: /config/assets
          readOnly: true
        - name: oidc-keys
          mountPath: /secrets/oidc-keys
          readOnly: true
        - name: tmp
          mountPath: /tmp

        livenessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi

      volumes:
      - name: config
        secret:
          secretName: authelia-config
          defaultMode: 0400
      - name: users
        secret:
          secretName: authelia-users
          defaultMode: 0400
      - name: assets
        configMap:
          name: authelia-assets
          defaultMode: 0644
      - name: oidc-keys
        secret:
          secretName: authelia-oidc-keys
          defaultMode: 0400
      - name: tmp
        emptyDir: {}
