---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "sabnzbd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sabnzbd.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command:
        - sh
        - -c
        - |
          chown -R {{ .Values.env.PUID }}:{{ .Values.env.PGID }} /config
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: sabnzbd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        - name: PUID
          value: {{ .Values.env.PUID | quote }}
        - name: PGID
          value: {{ .Values.env.PGID | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: {{ .Values.persistence.downloads.mountPath }}
        - name: incomplete
          mountPath: {{ .Values.persistence.incomplete.mountPath }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "sabnzbd.fullname" . }}-config
      - name: downloads
        hostPath:
          path: {{ .Values.persistence.downloads.hostPath }}
          type: Directory
      - name: incomplete
        hostPath:
          path: {{ .Values.persistence.incomplete.hostPath }}
          type: DirectoryOrCreate
