---
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName | default (printf "%s-secrets" (include "sonarr.fullname" .)) }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}

  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: {{ .Values.externalSecrets.secretName | default (printf "%s-secrets" (include "sonarr.fullname" .)) }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          {{- include "sonarr.labels" . | nindent 10 }}

  data:
  {{- range .Values.externalSecrets.secrets }}
  - secretKey: {{ .name }}
    remoteRef:
      key: {{ .key }}
  {{- end }}
{{- end }}
