---
# ExternalSecret for Sonarr - pulls API key from Bitwarden
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secrets
  namespace: default
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: sonarr-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app: sonarr

  # Pull secrets from Bitwarden
  data:
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr-api-key  # Name in Bitwarden Secrets Manager
