---
# Example ExternalSecret - pulls a test secret from Bitwarden
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: test-secret
    creationPolicy: Owner

  data:
    # Example: pull a secret named "test-secret" from Bitwarden
    - secretKey: password
      remoteRef:
        key: test-secret  # Name of secret in Bitwarden Secrets Manager
