---
{{- if .Values.machineLearning.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.machineLearning.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "immich.name" . }}-machine-learning
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
