apiVersion: v2
name: coreyalan-com-staging
description: CoreyAlan.com - Staging Environment
type: application
version: 1.0.0
appVersion: "0.2.1"
keywords:
  - coreyalan
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
dependencies:
  - name: staging-app
    version: "0.3.0"
    repository: "file://../../charts/staging-app"
