---
{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless.fullname" . }}-redis
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paperless.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - name: redis
          containerPort: {{ .Values.redis.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
{{- end }}
