---
# ServiceAccount for Bitwarden sync job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden-sync
  namespace: secrets-vault
---
# Role to manage secrets in secrets-vault namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitwarden-sync
  namespace: secrets-vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitwarden-sync
  namespace: secrets-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bitwarden-sync
subjects:
  - kind: ServiceAccount
    name: bitwarden-sync
    namespace: secrets-vault
