---
# Gitea database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-database
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-database
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gitea-database
    - extract:
        key: gitea-database-user
    - extract:
        key: gitea-database-password
---
# Gitea security tokens
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-security
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-security
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gitea-secret-key
    - extract:
        key: gitea-internal-token
    - extract:
        key: gitea-lfs-jwt-secret
    - extract:
        key: gitea-cookie-name
---
# Gitea OAuth2 credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gitea-oidc-client-id
    - extract:
        key: gitea-oidc-client-secret
---
# Email credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-email
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-email
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: email-host
    - extract:
        key: email-user
    - extract:
        key: email-password
