---
# Gitea database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-database
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: gitea-database
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: gitea-database
        property: value
    - secretKey: user
      remoteRef:
        key: gitea-database-user
        property: value
    - secretKey: password
      remoteRef:
        key: gitea-database-password
        property: value
---
# Gitea security tokens
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-security
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: gitea-security
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: gitea-secret-key
        property: value
    - secretKey: internal-token
      remoteRef:
        key: gitea-internal-token
        property: value
    - secretKey: lfs-jwt-secret
      remoteRef:
        key: gitea-lfs-jwt-secret
        property: value
    - secretKey: cookie-name
      remoteRef:
        key: gitea-cookie-name
        property: value
---
# Gitea OAuth2 credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: gitea-oauth
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: gitea-oidc-client-id
        property: value
    - secretKey: client-secret
      remoteRef:
        key: gitea-oidc-client-secret
        property: value
---
# Email credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-email
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: gitea-email
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: email-host
        property: value
    - secretKey: user
      remoteRef:
        key: email-user
        property: value
    - secretKey: password
      remoteRef:
        key: email-password
        property: value
