---
apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-db-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: gitea
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: gitea-db-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          set -e
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres-rw -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

          echo "Creating Gitea database and user..."

          # Create user if it doesn't exist
          PGPASSWORD="$POSTGRES_PASSWORD" psql -h postgres-rw -U postgres -tc \
            "SELECT 1 FROM pg_user WHERE usename = '$DB_USER'" | grep -q 1 || \
          PGPASSWORD="$POSTGRES_PASSWORD" psql -h postgres-rw -U postgres -c \
            "CREATE USER \"$DB_USER\" WITH PASSWORD '$DB_PASSWORD';"

          # Create database if it doesn't exist
          PGPASSWORD="$POSTGRES_PASSWORD" psql -h postgres-rw -U postgres -tc \
            "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1 || \
          PGPASSWORD="$POSTGRES_PASSWORD" psql -h postgres-rw -U postgres -c \
            "CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USER\";"

          # Grant privileges
          PGPASSWORD="$POSTGRES_PASSWORD" psql -h postgres-rw -U postgres -c \
            "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"

          echo "Database initialization complete!"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-superuser
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gitea-database
              key: value
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gitea-database
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-database
              key: password
