apiVersion: v2
name: capturly-web-staging
description: Capturly Web - Staging Environment
type: application
version: 1.0.0
appVersion: "v1.3.0"
keywords:
  - capturly
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
dependencies:
  - name: staging-app
    version: "0.1.0"
    repository: "file://../../charts/staging-app"
