---
# Grafana admin credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
        property: value
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
        property: value
---
# Grafana OAuth credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oauth
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: grafana-oidc-client-id
        property: value
    - secretKey: client-secret
      remoteRef:
        key: grafana-oidc-client-secret
        property: value
