---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.23.0
    helm:
      valuesObject:
        # Deployment mode - single binary for simplicity
        deploymentMode: SingleBinary

        # Single binary configuration
        singleBinary:
          replicas: 1

          # Node placement
          nodeSelector:
            kubernetes.io/hostname: blacktalon

          # Resources
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

          # Persistence
          persistence:
            enabled: true
            storageClass: local-path
            size: 50Gi

        # Loki configuration
        loki:
          auth_enabled: false

          commonConfig:
            replication_factor: 1

          storage:
            type: filesystem

          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h

          # Retention
          limits_config:
            retention_period: 30d
            max_query_length: 0h
            max_query_parallelism: 32

          # Compactor for retention enforcement
          compactor:
            retention_enabled: true
            delete_request_store: filesystem

        # Monitoring
        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false

        # Service configuration
        gateway:
          enabled: false

        # Test pod disabled
        test:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
