---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NX211/homelab-infra.git
    targetRevision: HEAD
    path: helm-charts/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Sync waves to ensure ExternalSecret creates the secret before Cluster uses it
  syncWaves:
    - name: secrets
      wave: 0
    - name: cluster
      wave: 1
