---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wizarr.fullname" . }}
  labels:
    {{- include "wizarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wizarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wizarr.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: wizarr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: database
          mountPath: /data/database
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: {{ include "wizarr.fullname" . }}-config
