---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thirteen-ft-ladder.fullname" . }}
  labels:
    {{- include "thirteen-ft-ladder.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "thirteen-ft-ladder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thirteen-ft-ladder.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: thirteen-ft-ladder
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
