apiVersion: v2
name: jlshaw-link-staging
description: JL Shaw Link - Staging Environment
type: application
version: 1.0.0
appVersion: "v0.1.1"
keywords:
  - jlshaw
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
