apiVersion: v2
name: jlshaw-link-staging
description: JL Shaw Link - Staging Environment
type: application
version: 1.0.0
appVersion: "v0.1.13"
keywords:
  - jlshaw
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
dependencies:
  - name: staging-app
    version: "0.1.0"
    repository: "file://../../charts/staging-app"
