---
{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  labels:
    {{- include "argocd-wrapper.labels" . | nindent 4 }}
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
{{- end }}
