apiVersion: v2
name: reggiesbbq-staging
description: Reggie's BBQ - Staging Environment
type: application
version: 1.0.0
appVersion: "0.8.2"
keywords:
  - reggiesbbq
  - nextjs
  - staging
maintainers:
  - name: Homelab Admin
dependencies:
  - name: staging-app
    version: "0.8.4"
    repository: "file://../../charts/staging-app"
