{{- if .Values.gcrPullSecret.bitwardenKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "staging-app.gcrSecretName" . }}
  labels:
    {{- include "staging-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ include "staging-app.secretStoreName" . }}
    kind: ClusterSecretStore
  target:
    name: {{ include "staging-app.gcrSecretName" . }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{`{{ printf "{\"auths\":{\"us-central1-docker.pkg.dev\":{\"username\":\"_json_key\",\"password\":%s}}}" (.gcrKey | toJson) }}`}}
  data:
    - secretKey: gcrKey
      remoteRef:
        key: {{ .Values.gcrPullSecret.bitwardenKey }}
{{- end }}
