---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.instances }}

  # PostgreSQL configuration
  imageName: {{ .Values.imageName }}

  postgresql:
    parameters:
      {{- range $key, $value := .Values.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}

  # Storage configuration
  storage:
    size: {{ .Values.storage.size }}
    storageClass: {{ .Values.storage.storageClass }}

  # Superuser secret
  superuserSecret:
    name: postgres-superuser

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: {{ .Values.bootstrap.initdb.database }}
      owner: {{ .Values.bootstrap.initdb.owner }}
      {{- if .Values.bootstrap.initdb.postInitApplicationSQL }}
      postInitApplicationSQL:
        {{- toYaml .Values.bootstrap.initdb.postInitApplicationSQL | nindent 8 }}
      {{- end }}

  {{- if .Values.backup.enabled }}
  # Automated backups
  backup:
    barmanObjectStore:
      {{- toYaml .Values.backup.barmanObjectStore | nindent 6 }}
    retentionPolicy: {{ .Values.backup.retentionPolicy | default "30d" }}
  {{- end }}

  # Node affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            {{- range $key, $value := .Values.nodeSelector }}
            - {{ $value }}
            {{- end }}

  # Resources
  resources:
    {{- toYaml .Values.resources | nindent 4 }}

  # Monitoring
  monitoring:
    enablePodMonitor: {{ .Values.monitoring.enablePodMonitor }}
