---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-superuser
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: postgres
        password: {{ `{{ .password }}` }}
  data:
    - secretKey: password
      remoteRef:
        key: postgres-root-password
        property: value
